language: python
python:
    #- 2.7
    - 3.4
    - 3.5
install:
    - pip install -e .
    - pip install coveralls requests-mock
script:
    - coverage run --source=xirvik '--omit=xirvik/test/*' -m unittest -v
after_success:
    coveralls
