language: python
python:
  - 3.6
  - 3.7
  - '3.8-dev'
install:
  - pip install -e .
  - pip install coveralls nose requests-mock
  # Temporary until https://github.com/eweast/BencodePy/pull/5 is merged
  - 'pip install --upgrade -e git+https://github.com/Tatsh/BencodePy.git@py2#egg=bencodepy'
script:
  - coverage run --source=xirvik '--omit=xirvik/test/*' -m nose -x
after_success: coveralls
