[tool.poetry]
authors = ["Fa An <2998784916@qq.com>"]
classifiers = ["Topic :: Software Development :: Libraries :: Python Modules"]
description = "Command line utilities for interfacing with Xirvik."
documentation = "https://xirvik-tools.readthedocs.io/"
homepage = "https://github.com/Tatsh/xirvik-tools"
include = ["LaunchAgents", "systemd"]
keywords = ["command line", "utilities", "xirvik"]
license = "MIT"
name = "xirvik-tools"
packages = [{ include = "xirvik" }]
readme = "README.md"
version = "1.0.0"

[tool.poetry.dependencies]
python = "^3.10"
unidecode = "^1.3.6"
beautifulsoup4 = "^4.12.0"
cached-property = "^1.5.2"
click = "^8.1.3"
html5lib = "^1.1"
loguru = "^0.6.0"
pyyaml = "^6.0"
requests = "^2.28.2"
tabulate = "^0.9.0"
urllib3 = "^1.26.15"
xdg = "^6.0.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.testing]
optional = true

[tool.poetry.group.dev.dependencies]
mypy = "^1.1.1"
pylint = "^2.17.0"
rope = "^1.7.0"
types-beautifulsoup4 = "^4.11.6.7"
types-requests = "^2.28.11.15"
types-tabulate = "^0.9.0.1"
yapf = "^0.32.0"
toml = "^0.10.2"
pylint-quotes = "^0.2.3"

[tool.poetry.group.docs.dependencies]
sphinx = "^6.1.3"

[tool.poetry.group.testing.dependencies]
mock = "^5.0.1"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
requests-mock = "^1.10.0"
coveralls = "^3.3.1"

[tool.poetry.group.packaging.dependencies]
wheel = "^0.40.0"
twine = "^4.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
xirvik = "xirvik.commands:xirvik"
