---
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          pip install -e '.[testing]'
      - name: Lint with mypy
        run: mypy .
      - if: matrix.python-version == 3.8
        name: Lint with Pylint
        run: |
          pip install pylint
          pylint xirvik setup.py
      - if: matrix.python-version == 3.8
        name: Check spelling
        run: |
          npm install -g cspell
          cspell --no-progress --config ./.vscode/cspell.json './**/*'  './**/.*'
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
'on':
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
