---
name: Upload Python Package
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install --with=packaging
      - env:
          TWINE_NON_INTERACTIVE: '1'
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        name: Build and publish
        run: |
          poetry build
          twine upload --disable-progress-bar dist/*
'on':
  release:
    types:
      - created
