---
name: Tests
jobs:
  test:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install --with=testing
      - name: Run tests
        run: poetry run pytest --cov=xirvik --cov-branch
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.python-version == 3.10
        name: Coveralls
        run: poetry run coveralls --service=github
    strategy:
      matrix:
        python-version:
          - '3.10'
'on':
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
